export const initialEmployees = [
  { ad: "Elvin", soyad: "Quliyev", maas: 1200, yas: 28, staj: 5, saha: "Frontend" },
  { ad: "Kamran", soyad: "Əliyev", maas: 1500, yas: 32, staj: 8, saha: "Backend" },
  { ad: "Nicat", soyad: "Hüseynov", maas: 1100, yas: 26, staj: 4, saha: "Mobile" },
  { ad: "Murad", soyad: "İbrahimov", maas: 1700, yas: 34, staj: 9, saha: "DevOps" },
  { ad: "Orxan", soyad: "Səfərov", maas: 900, yas: 24, staj: 2, saha: "Design" },
  { ad: "Rauf", soyad: "Rzayev", maas: 1400, yas: 30, staj: 6, saha: "Data Science" },
  { ad: "Tural", soyad: "Məmmədov", maas: 1300, yas: 29, staj: 5, saha: "Frontend" },
  { ad: "Zaur", soyad: "Ələkbərov", maas: 1250, yas: 27, staj: 4, saha: "QA" },
  { ad: "Samir", soyad: "Babayev", maas: 1600, yas: 33, staj: 7, saha: "Backend" },
  { ad: "Fuad", soyad: "Kazımov", maas: 1000, yas: 25, staj: 3, saha: "Mobile" },
  { ad: "Vüsal", soyad: "Tağıyev", maas: 1350, yas: 30, staj: 6, saha: "Frontend" },
  { ad: "Emin", soyad: "Əhmədov", maas: 1450, yas: 31, staj: 7, saha: "DevOps" },
  { ad: "Nurlan", soyad: "Süleymanov", maas: 950, yas: 23, staj: 2, saha: "Design" },
  { ad: "Cavid", soyad: "Qasımov", maas: 1700, yas: 35, staj: 10, saha: "Backend" },
  { ad: "Rəşad", soyad: "Əzizov", maas: 1200, yas: 28, staj: 5, saha: "Data Science" },
  { ad: "Fərid", soyad: "Nağıyev", maas: 1300, yas: 29, staj: 6, saha: "QA" },
  { ad: "Sahil", soyad: "İsmayılov", maas: 1050, yas: 26, staj: 3, saha: "Frontend" },
  { ad: "Əli", soyad: "Səmədov", maas: 1500, yas: 32, staj: 8, saha: "Backend" },
  { ad: "İlqar", soyad: "Həsənov", maas: 1100, yas: 27, staj: 4, saha: "Mobile" },
  { ad: "Tofiq", soyad: "Əliyev", maas: 1600, yas: 34, staj: 9, saha: "DevOps" },
  { ad: "Süleyman", soyad: "Zeynalov", maas: 980, yas: 24, staj: 2, saha: "Design" },
  { ad: "İbrahim", soyad: "Qəhrəmanov", maas: 1400, yas: 30, staj: 6, saha: "Data Science" },
  { ad: "Məmməd", soyad: "Ələsgerov", maas: 1300, yas: 28, staj: 5, saha: "Frontend" },
  { ad: "Ramin", soyad: "Şükürov", maas: 1250, yas: 27, staj: 4, saha: "QA" },
  { ad: "Sadiq", soyad: "Orucov", maas: 1500, yas: 33, staj: 8, saha: "Backend" },
  { ad: "Xəyal", soyad: "Namazov", maas: 1020, yas: 25, staj: 3, saha: "Mobile" },
  { ad: "Əhməd", soyad: "Rəhimov", maas: 1350, yas: 29, staj: 6, saha: "Frontend" },
  { ad: "Teymur", soyad: "Fətəliyev", maas: 1450, yas: 31, staj: 7, saha: "DevOps" },
  { ad: "Elçin", soyad: "Qarayev", maas: 990, yas: 23, staj: 2, saha: "Design" },
  { ad: "Nazim", soyad: "İmanov", maas: 1700, yas: 35, staj: 10, saha: "Backend" },
  { ad: "Cavidan", soyad: "Əlizadə", maas: 1200, yas: 28, staj: 5, saha: "Data Science" },
  { ad: "Röyal", soyad: "Zamanov", maas: 1300, yas: 29, staj: 6, saha: "QA" },
  { ad: "Səməd", soyad: "Vəliyev", maas: 1050, yas: 26, staj: 3, saha: "Frontend" },
  { ad: "Ülvi", soyad: "Cəfərov", maas: 1500, yas: 32, staj: 8, saha: "Backend" },
  { ad: "Şamil", soyad: "Bədəlov", maas: 1100, yas: 27, staj: 4, saha: "Mobile" },
  { ad: "Etibar", soyad: "Şahverdiyev", maas: 1600, yas: 34, staj: 9, saha: "DevOps" },
  { ad: "Adil", soyad: "Vahabov", maas: 970, yas: 24, staj: 2, saha: "Design" },
  { ad: "Elgiz", soyad: "Bayramov", maas: 1400, yas: 30, staj: 6, saha: "Data Science" },
  { ad: "Zakir", soyad: "Qurbanov", maas: 1300, yas: 28, staj: 5, saha: "Frontend" },
  { ad: "Faiq", soyad: "Məlikov", maas: 1250, yas: 27, staj: 4, saha: "QA" },
  { ad: "Togrul", soyad: "Mustafayev", maas: 1500, yas: 33, staj: 8, saha: "Backend" },
  { ad: "Ümid", soyad: "Əkbərov", maas: 1000, yas: 25, staj: 3, saha: "Mobile" },
  { ad: "Fikrət", soyad: "Şirinov", maas: 1350, yas: 29, staj: 6, saha: "Frontend" },
  { ad: "Yusif", soyad: "Mehdiyev", maas: 1450, yas: 31, staj: 7, saha: "DevOps" },
  { ad: "Rüfət", soyad: "Nəcəfov", maas: 950, yas: 23, staj: 2, saha: "Design" },
  { ad: "Bəxtiyar", soyad: "Salmanov", maas: 1700, yas: 35, staj: 10, saha: "Backend" },
  { ad: "Vaqif", soyad: "Yusubov", maas: 1200, yas: 28, staj: 5, saha: "Data Science" },
  { ad: "Şahin", soyad: "Hacıyev", maas: 1300, yas: 29, staj: 6, saha: "QA" }
];